# Generated by Django 5.2 on 2025-04-05 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('languages', models.CharField(choices=[('عربي', 'عربي'), ('إنجليزي', 'إنجليزي'), ('عربي, إنجليزي', 'عربي, إنجليزي')], max_length=100)),
                ('favorites', models.PositiveIntegerField(default=0)),
                ('addedAt', models.DateTimeField(auto_now_add=True)),
                ('cover', models.ImageField(default='placeholders/no_www.png', upload_to='sites/')),
            ],
            options={
                'verbose_name': 'موقع',
                'verbose_name_plural': 'مواقع',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('جديد', 'جديد'), ('قيد الإنتظار', 'قيد الإنتظار'), ('تم حلها', 'تم حلها'), ('مغلق', 'مغلق')], default='جديد', max_length=50)),
                ('category', models.CharField(choices=[('مشكلة تقنية', 'مشكلة تقنية'), ('إقتراح', 'إقتراح'), ('آخرى', 'آخرى')], max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'تقارير',
            },
        ),
        migrations.CreateModel(
            name='ReportReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رد',
                'verbose_name_plural': 'ردود',
            },
        ),
        migrations.CreateModel(
            name='FavoriteSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_by', to='mysite.site')),
            ],
            options={
                'verbose_name': 'المفضلة',
                'verbose_name_plural': 'المفضلات',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('language', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=150)),
                ('duration', models.FloatField()),
                ('duration_format', models.CharField(choices=[('دقائق', 'دقائق'), ('ساعات', 'ساعات')], default='ساعات', max_length=50)),
                ('author', models.CharField(max_length=150)),
                ('addedAt', models.DateTimeField(auto_now_add=True)),
                ('cover', models.ImageField(default='placeholders/no_learning.png', upload_to='courses/')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.site')),
            ],
            options={
                'verbose_name': 'دورة',
                'verbose_name_plural': 'دورات',
            },
        ),
    ]
